etablissement_homepage:
    path:     /
    defaults: { _controller: EtablissementBundle:Etablissement:listEtablissement}
list_Etablissement:
    path:     /listEtablissement
    defaults: { _controller: EtablissementBundle:Etablissement:listEtablissement }
detailed_Etablissement:
    path:     /detailedEtablissement/{id}
    defaults: { _controller: EtablissementBundle:Etablissement:showdetailed}
ajax_search:
    path:     /search
    defaults: { _controller: EtablissementBundle:Etablissement:search}
add_comment:
    path:     /addcomment
    defaults: { _controller: EtablissementBundle:Etablissement:addComment}
delete_comment:
    path:     /deletecomment/{id}
    defaults: { _controller: EtablissementBundle:Etablissement:deleteComment}
add_reclamation:
    path:     /addReclamation/{id}
    defaults: { _controller: EtablissementBundle:Etablissement:addReclamation}
list_reclamation:
    path:     /listReclamation
    defaults: { _controller: EtablissementBundle:Etablissement:listReclamation}
delete_reclamation:
    path:     /deleteReclamation/{id}
    defaults: { _controller: EtablissementBundle:Etablissement:deleteReclamation}
update_reclamation:
    path:     /updateReclamation/{id}
    defaults: { _controller: EtablissementBundle:Etablissement:updateReclamation}



