admin_homepage:
    path:     /
    defaults: { _controller: adminBundle:Default:index }

afficher_ctegorie:
    path:     /admin/afficherCtegorie
    defaults: { _controller: adminBundle:DashboardController:afficherCtegorie }
supprimerCategorie:
    path:     /admin/supprimerCategorie/{id}
    defaults: { _controller: adminBundle:DashboardController:supprimerCategorie }
supprimerClub:
    path:     /admin/supprimerClub/{id}
    defaults: { _controller: adminBundle:DashboardController:supprimerClub }
modifierClub:
    path:     /admin/modifierClub/{id}
    defaults: { _controller: adminBundle:DashboardController:modifierClub }
modifierCategorie:
    path:     /admin/modifierCategorie/{id}
    defaults: { _controller: adminBundle:DashboardController:modifierCategorie }
afficherAbonne:
    path:     /admin/afficherAbonne
    defaults: { _controller: adminBundle:DashboardController:afficherAbonne }
supprimerInscription:
    path:     /admin/supprimerInscription/{id}
    defaults: { _controller: adminBundle:DashboardController:supprimerInscription }
modifierInscription:
    path:     /admin/modifierInscription/{id}
    defaults: { _controller: adminBundle:DashboardController:modifierInscription }
ajouterClub:
    path:     /admin/ajouterClub
    defaults: { _controller: adminBundle:DashboardController:ajouterClub }
ajouterCategorie:
    path:     /admin/ajouterCategorie
    defaults: { _controller: adminBundle:DashboardController:ajouterCategorie }
testerEmail:
    path:     /admin/testerEmail
    defaults: { _controller: adminBundle:DashboardController:testerEmail }
galerie:
    path:     /admin/galerie
    defaults: { _controller: adminBundle:DashboardController:galerie }
export:
    path:     /admin/export
    defaults: { _controller: adminBundle:DashboardController:export }