admin_homepage:
    path:     /admin
    defaults: { _controller: AdminBundle:Default:index }

afficherCat:
    path:     /afficherCat
    defaults: { _controller: AdminBundle:Dashboard:afficher }


supprimerCategorie:
    path:     /supprimerCategorie/{id}
    defaults: { _controller: AdminBundle:Dashboard:supprimerCategorie }

supprimerEvenement:
    path:     /supprimerEvenement/{id}
    defaults: { _controller: AdminBundle:Dashboard:supprimerEvenement }

modifiercategorie:
    path:     /modifiercategorie/{id}
    defaults: { _controller: AdminBundle:Dashboard:modifiercategorie }
modifierEvenement:
    path:     /modifierEvenement/{id}
    defaults: { _controller: AdminBundle:Dashboard:modifierEvenement }
ajouterEvenement:
    path:     /ajouterEvenement
    defaults: { _controller: AdminBundle:Dashboard:ajouterEvenement }
ajouterCategorie:
    path:     /ajouterCategorie
    defaults: { _controller: AdminBundle:Dashboard:ajouterCategorie }
