admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

afficherCat:
    path:     /admin/afficherCat
    defaults: { _controller: AdminBundle:Dashboard:afficher }


supprimerCategorie:
    path:     /admin/supprimerCategorie/{id}
    defaults: { _controller: AdminBundle:Dashboard:supprimerCategorie }

supprimerEvenement:
    path:     /admin/supprimerEvenement/{id}
    defaults: { _controller: AdminBundle:Dashboard:supprimerEvenement }

modifiercategorie:
    path:     admin//modifiercategorie/{id}
    defaults: { _controller: AdminBundle:Dashboard:modifiercategorie }
modifierEvenement:
    path:     /admin/modifierEvenement/{id}
    defaults: { _controller: AdminBundle:Dashboard:modifierEvenement }
ajouterEvenement:
    path:     /admin/ajouterEvenement
    defaults: { _controller: AdminBundle:Dashboard:ajouterEvenement }
ajouterCategorie:
    path:     /admin/ajouterCategorie
    defaults: { _controller: AdminBundle:Dashboard:ajouterCategorie }
