evenement_homepage:
    path:     /
    defaults: { _controller: EvenementBundle:Default:index }

afficher:
    path:     /user/afficher/{id}
    defaults: { _controller: EvenementBundle:Evenement:afficher }

ajouter:
    path:     /user/ajouter
    defaults: { _controller: EvenementBundle:Evenement:ajouter }

rechercher:
    path:     /user/rechercher
    defaults: { _controller: EvenementBundle:Evenement:rechercher }

modifier:
    path:     /user/modifier/{id}
    defaults: { _controller: EvenementBundle:Evenement:modifier }

supprimer:
    path:     /user/supprimer/{id}
    defaults: { _controller: EvenementBundle:Evenement:supprimer }

affichercategorie:
    path:     /user/affichercategorie
    defaults: { _controller: EvenementBundle:Evenement:affichercategorie }

ajouterReservation:
    path:     /user/ajouterReservation/{id}
    defaults: { _controller: EvenementBundle:Evenement:ajouterReservation }
