<?php

namespace Gestion_BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a
                FROM Gestion_BlogBundle:Article a
                WHERE a.titre LIKE :terme')
            ->setParameter('terme', '%'.$str.'%')
            ->setMaxResults(5)->getResult();

    }


}
