<?php

namespace gererClubBundle\Repository;

/**
 * categorieClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieClubRepository extends \Doctrine\ORM\EntityRepository
{
}
