<?php

namespace gererClubBundle\Repository;

/**
 * commantaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commantaireRepository extends \Doctrine\ORM\EntityRepository
{
}
