<?php

namespace gererClubBundle\Repository;

/**
 * inscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class inscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
