<?php

namespace gererClubBundle\Repository;

/**
 * newsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class newsRepository extends \Doctrine\ORM\EntityRepository
{
}
