<?php

namespace adminBundle\Repository;

/**
 * galerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class galerieRepository extends \Doctrine\ORM\EntityRepository
{
}
