<?php

namespace EtablissementBundle\Repository;

/**
 * EtablissementcommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementcommentRepository extends \Doctrine\ORM\EntityRepository
{
}
