<?php

namespace EvenementBundle\Repository;

/**
 * categorieEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieEvenementRepository extends \Doctrine\ORM\EntityRepository
{
}
