<?php

namespace EvenementBundle\Repository;

/**
 * inscriptionEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class inscriptionEmailRepository extends \Doctrine\ORM\EntityRepository
{
}
