cour._homepage:
    path:     /
    defaults: { _controller: Cour_Bundle:Default:index }


cour_read:
    path:     /Lire/{id}
    defaults: { _controller: Cour_Bundle:Default:read }

cour_dowload:
    path:     /download/{id}
    defaults: { _controller: Cour_Bundle:Default:download }
