gerer_club_homepage:
    path:     /
    defaults: { _controller: gererClubBundle:Default:index }
club:
    path:     /user/clubs
    defaults: { _controller: gererClubBundle:club:afficher }
afficherClubSelonClub:
    path:     /user/afficherClubSelonClub/{id}
    defaults: { _controller: gererClubBundle:club:afficherClubSelonClub }
inscription:
    path:     /user/inscription/{id}
    defaults: { _controller: gererClubBundle:club:inscription }
galerie:
    path:     /user/galerie
    defaults: { _controller: gererClubBundle:club:galerie }
ajouterUneEtoile:
    path:     /user/ajouterUneEtoile/{id}/{nombre}
    defaults: { _controller: gererClubBundle:club:ajouterUneEtoile }
ajouterCommantaire:
    path:     /user/ajouterCommantaire/{id}
    defaults: { _controller: gererClubBundle:club:ajouterCommantaire }
newsletterInscription:
    path:     /user/newsletterInscription
    defaults: { _controller: gererClubBundle:club:newsletterInscription }