<?php

namespace projetBundle\Repository;

/**
 * eleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eleveRepository extends \Doctrine\ORM\EntityRepository
{
}
