<?php

namespace projetBundle\Repository;

/**
 * eleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eleveRepository extends \Doctrine\ORM\EntityRepository
{

    public function getstat()
    {



        $query = $this->getEntityManager()
            ->createQuery("SELECT count(e) as nombre , e.Age as age from projetBundle:eleve e GROUP BY e.Age");

        return $query->getResult();
    }

}
