<?php

namespace projetBundle\Repository;

/**
 * parentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class parentsRepository extends \Doctrine\ORM\EntityRepository
{
}
