<?php

namespace projetBundle\Repository;

/**
 * personnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personnelRepository extends \Doctrine\ORM\EntityRepository
{
}
