<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEvsxtq3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEvsxtq3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEvsxtq3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEvsxtq3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerEvsxtq3\appDevDebugProjectContainer([
    'container.build_hash' => 'Evsxtq3',
    'container.build_id' => '7cd0924f',
    'container.build_time' => 1581209185,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEvsxtq3');
